Repository nextcloud/approval, pull requests merged in 2022-12, with the labels that each got.

#39 Add auto-deploy config
  .github/workflows/appstore-build-publish.yml
  .gitignore
  makefile
Labels: enhancement

#42 Avoid empty string default for notnull columns
  js/approval-adminSettings.js
  js/approval-adminSettings.js.map
  lib/Migration/Version000004Date20210331142734.php
  lib/Migration/Version000004Date20210427102750.php
  lib/Migration/Version000004Date20210427142434.php
  src/components/AdminSettings.vue
Labels: bug

#40 Upgrade phpunit testing suite
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/tests.yml
  tests/phpunit.xml
Labels: testing
